name: Scalpel Build on Pull Request.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    name: (${{ matrix.target}}, ${{ matrix.cfg_release_channel }})
    strategy:
      matrix:
        target: [
          x86_64-unknown-linux-gnu,
        ]
        cfg_release_channel: [ nightly, stable]


    steps:
    - uses: actions/checkout@v3
    - name: install rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
        sh rustup-init.sh -y --default-toolchain none
        rustup target add ${{ matrix.target }}
        rustup default ${{ matrix.cfg_release_channel }}
    - name: Build
      run: |
        rustc -Vv
        cargo -V
        cargo build --verbose
    - name: Run tests
      run: |
        rustc -Vv
        cargo -V
        cargo test --verbose
    - name: Build with Python Bindings
      run: |
        rustc -Vv
        cargo -V
        cargo build --verbose --features python-bindings
    - name: Run tests with Python Bindings
      run: |
        rustc -Vv
        cargo -V
        cargo test --verbose --features python-bindings
